CREATE TABLE [Stage].[BAPUSOECMFP] (
    [CMSTAT]   VARCHAR (1)     NULL,
    [CMDTCR]   NUMERIC (7)     NULL,
    [CMDTUP]   NUMERIC (7)     NULL,
    [CMBRCH]   VARCHAR (2)     NULL,
    [CMCUST]   VARCHAR (5)     NULL,
    [CMSHIP]   NUMERIC (3)     NULL,
    [CMLIMT]   NUMERIC (11, 2) NULL,
    [CMCHLD]   VARCHAR (1)     NULL,
    [CMOBLC]   NUMERIC (11, 2) NULL,
    [CMOBLS]   NUMERIC (11, 2) NULL,
    [CMABAL]   NUMERIC (11, 2) NULL,
    [CMLPMT]   NUMERIC (11, 2) NULL,
    [CMLINA]   NUMERIC (11, 2) NULL,
    [CMLORA]   NUMERIC (11, 2) NULL,
    [CMNAME]   VARCHAR (35)    NULL,
    [CMADD1]   VARCHAR (30)    NULL,
    [CMADD2]   VARCHAR (30)    NULL,
    [CMCITY]   VARCHAR (20)    NULL,
    [CMPROV]   VARCHAR (2)     NULL,
    [CMPOST]   VARCHAR (6)     NULL,
    [CMPHN1]   VARCHAR (10)    NULL,
    [CMPHN2]   VARCHAR (10)    NULL,
    [CMPST#]   VARCHAR (15)    NULL,
    [CMFST#]   VARCHAR (15)    NULL,
    [CMCNTC]   VARCHAR (20)    NULL,
    [CMROUT]   VARCHAR (4)     NULL,
    [CMSMRT]   VARCHAR (10)    NULL,
    [CMDTLI]   NUMERIC (7)     NULL,
    [CMDTLO]   NUMERIC (7)     NULL,
    [CMDTLP]   NUMERIC (7)     NULL,
    [CMMRKS]   VARCHAR (4)     NULL,
    [CMTERM]   VARCHAR (1)     NULL,
    [CMBYGP]   VARCHAR (4)     NULL,
    [CMSLS#]   VARCHAR (4)     NULL,
    [CMLANG]   VARCHAR (1)     NULL,
    [CMCDSF]   VARCHAR (1)     NULL,
    [CMPSLC]   VARCHAR (1)     NULL,
    [CMPROC]   VARCHAR (1)     NULL,
    [CMDLRC]   VARCHAR (1)     NULL,
    [CMMKGR]   VARCHAR (4)     NULL,
    [CMAUTH]   VARCHAR (1)     NULL,
    [CMINAC]   VARCHAR (1)     NULL,
    [CMCHBR]   VARCHAR (2)     NULL,
    [CMSTMT]   VARCHAR (1)     NULL,
    [CMEFST]   VARCHAR (1)     NULL,
    [CMPORQ]   VARCHAR (1)     NULL,
    [CMPRCF]   VARCHAR (1)     NULL,
    [CMCDSP]   NUMERIC (5, 2)  NULL,
    [CMTFAX]   VARCHAR (10)    NULL,
    [CMTMAL]   VARCHAR (1)     NULL,
    [CMCGRP]   VARCHAR (5)     NULL,
    [CMINTO]   VARCHAR (1)     NULL,
    [CMSTTO]   VARCHAR (1)     NULL,
    [CMCRDC]   VARCHAR (1)     NULL,
    [CMCURC]   VARCHAR (3)     NULL,
    [CMCSMK]   VARCHAR (1)     NULL,
    [CMINTY]   VARCHAR (1)     NULL,
    [CMDAYS]   NUMERIC (3)     NULL,
    [CMLST1]   VARCHAR (4)     NULL,
    [CMLST2]   VARCHAR (4)     NULL,
    [CMTYPE]   VARCHAR (1)     NULL,
    [CMPREM]   VARCHAR (1)     NULL,
    [CMDTIA]   NUMERIC (7)     NULL,
    [CMCNRQ]   VARCHAR (1)     NULL,
    [CMDSMT]   VARCHAR (1)     NULL,
    [CMDSGP]   VARCHAR (4)     NULL,
    [CMPRTF]   VARCHAR (1)     NULL,
    [CMPROF]   VARCHAR (10)    NULL,
    [CMCASH]   VARCHAR (1)     NULL,
    [CMOLS1]   VARCHAR (4)     NULL,
    [CMOLS2]   VARCHAR (4)     NULL,
    [CMDTEX]   NUMERIC (7)     NULL,
    [CMWHSE]   VARCHAR (2)     NULL,
    [CMSTMF]   VARCHAR (1)     NULL,
    [CMLPIC]   VARCHAR (1)     NULL,
    [CMCELP]   VARCHAR (10)    NULL,
    [CMHDCH]   VARCHAR (1)     NULL,
    [CMSTGC]   VARCHAR (9)     NULL,
    [CMUSCU]   VARCHAR (1)     NULL,
    [CMOFSR]   VARCHAR (1)     NULL,
    [CMNTRC]   VARCHAR (1)     NULL,
    [CMEMPL]   VARCHAR (1)     NULL,
    [CMFRCL]   VARCHAR (1)     NULL,
    [CMCLS1]   VARCHAR (1)     NULL,
    [CMCLS2]   VARCHAR (1)     NULL,
    [CMCLS3]   VARCHAR (1)     NULL,
    [CMBRFX]   VARCHAR (1)     NULL,
    [CMLST3]   VARCHAR (4)     NULL,
    [CMPHLD]   VARCHAR (1)     NULL,
    [CMINTP]   VARCHAR (6)     NULL,
    [CMAUHF]   VARCHAR (1)     NULL,
    [CMTMCD]   VARCHAR (2)     NULL,
    [CMORNF]   VARCHAR (1)     NULL,
    [CMSTID]   VARCHAR (10)    NULL,
    [CMFRAP]   NUMERIC (5, 2)  NULL,
    [CMMALI]   VARCHAR (1)     NULL,
    [CMINTN]   VARCHAR (1)     NULL,
    [CMGOLD]   VARCHAR (1)     NULL,
    [CMWEBF]   VARCHAR (1)     NULL,
    [CMCRED]   VARCHAR (1)     NULL,
    [CMFEDC]   VARCHAR (9)     NULL,
    [CMOCYC]   VARCHAR (1)     NULL,
    [CMORBF]   VARCHAR (1)     NULL,
    [CMFRTX]   VARCHAR (1)     NULL,
    [AuditKey] INT             NULL
);


GO
CREATE CLUSTERED INDEX [cxStage_BAPUSOECMFP]
    ON [Stage].[BAPUSOECMFP]([CMCUST] ASC, [CMBRCH] ASC);

