CREATE TABLE [Stage].[BAPUSEMEMLP] (
    [EMSTAT]   VARCHAR (1)   NULL,
    [EMDTCR]   NUMERIC (7)   NULL,
    [EMDTUP]   NUMERIC (7)   NULL,
    [EMTMUP]   NUMERIC (7)   NULL,
    [EMENTY]   VARCHAR (4)   NULL,
    [EMEMLS]   VARCHAR (8)   NULL,
    [EMSUPP]   VARCHAR (8)   NULL,
    [EMBRCH]   VARCHAR (2)   NULL,
    [EMCUST]   VARCHAR (5)   NULL,
    [EMSHIP]   NUMERIC (3)   NULL,
    [EMRCTP]   VARCHAR (2)   NULL,
    [EMSNDF]   VARCHAR (1)   NULL,
    [EMEMAL]   VARCHAR (100) NULL,
    [EMPROC]   VARCHAR (1)   NULL,
    [EMDTUU]   NUMERIC (7)   NULL,
    [EMUSUP]   VARCHAR (10)  NULL,
    [EMDTSU]   NUMERIC (7)   NULL,
    [EMUPGM]   VARCHAR (10)  NULL,
    [EMSWPC]   VARCHAR (1)   NULL,
    [EMZNLY]   VARCHAR (1)   NULL,
    [AuditKey] INT           NULL
);


GO
CREATE CLUSTERED INDEX [cxStage_BAPUSEMEMLP]
    ON [Stage].[BAPUSEMEMLP]([EMCUST] ASC, [EMBRCH] ASC);

